-- Chạy toàn bộ file này một lần trong Supabase Dashboard > SQL Editor.
-- Khách có thể đọc; thành viên đã đăng nhập mới được đăng và xóa nội dung của chính mình.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  pinned boolean not null default false,
  flair text not null check (flair in ('Thông báo', 'Góp ý', 'Nhận xét', 'Hỏi đáp', 'Chia sẻ')),
  title varchar(120) not null check (char_length(title) between 3 and 120),
  excerpt text not null check (char_length(excerpt) between 3 and 2000),
  username varchar(40) not null default 'khach' check (char_length(username) between 2 and 40),
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  owner_token_hash text,
  is_demo boolean not null default false,
  score integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  username varchar(40) not null default 'khach' check (char_length(username) between 2 and 40),
  content text not null check (char_length(content) between 2 and 1000),
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  owner_token_hash text,
  created_at timestamptz not null default now()
);

alter table public.posts add column if not exists owner_token_hash text;
alter table public.comments add column if not exists owner_token_hash text;
alter table public.posts add column if not exists user_id uuid references auth.users(id) on delete set null default auth.uid();
alter table public.comments add column if not exists user_id uuid references auth.users(id) on delete set null default auth.uid();
alter table public.posts add column if not exists is_demo boolean not null default false;
alter table public.posts drop constraint if exists posts_flair_check;
alter table public.posts add constraint posts_flair_check check (flair in ('Thông báo', 'Góp ý', 'Nhận xét', 'Hỏi đáp', 'Chia sẻ'));

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists comments_post_id_idx on public.comments(post_id, created_at);

alter table public.posts enable row level security;
alter table public.comments enable row level security;

revoke all on table public.posts from anon, authenticated;
revoke all on table public.comments from anon, authenticated;
grant select, insert, delete on table public.posts to anon, authenticated;
grant select, insert, delete on table public.comments to anon, authenticated;
grant usage, select on sequence public.posts_id_seq, public.comments_id_seq to anon, authenticated;

drop policy if exists "Public posts are readable" on public.posts;
create policy "Public posts are readable"
on public.posts for select
to anon, authenticated
using (true);

drop policy if exists "Visitors can create posts" on public.posts;
create policy "Visitors can create posts"
on public.posts for insert
to anon, authenticated
with check (
  pinned = false
  and score between 0 and 1
  and flair in ('Góp ý', 'Nhận xét', 'Hỏi đáp', 'Chia sẻ')
  and char_length(title) between 3 and 120
  and char_length(excerpt) between 3 and 2000
  and char_length(username) between 2 and 40
  and owner_token_hash ~ '^[0-9a-f]{64}$'
);

drop policy if exists "Public comments are readable" on public.comments;
create policy "Public comments are readable"
on public.comments for select
to anon, authenticated
using (true);

drop policy if exists "Visitors can create comments" on public.comments;
create policy "Visitors can create comments"
on public.comments for insert
to anon, authenticated
with check (
  char_length(username) between 2 and 40
  and char_length(content) between 2 and 1000
  and owner_token_hash ~ '^[0-9a-f]{64}$'
);

drop policy if exists "Owners can delete posts" on public.posts;
create policy "Owners can delete posts"
on public.posts for delete
to anon, authenticated
using (
  owner_token_hash = encode(
    extensions.digest(convert_to(current_setting('app.owner_token', true), 'UTF8'), 'sha256'),
    'hex'
  )
);

drop policy if exists "Owners can delete comments" on public.comments;
create policy "Owners can delete comments"
on public.comments for delete
to anon, authenticated
using (
  owner_token_hash = encode(
    extensions.digest(convert_to(current_setting('app.owner_token', true), 'UTF8'), 'sha256'),
    'hex'
  )
);

create or replace function public.delete_own_post(target_id bigint, raw_token text)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform set_config('app.owner_token', raw_token, true);
  delete from public.posts where id = target_id;
  return found;
end;
$$;

create or replace function public.delete_own_comment(target_id bigint, raw_token text)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform set_config('app.owner_token', raw_token, true);
  delete from public.comments where id = target_id;
  return found;
end;
$$;

revoke execute on function public.delete_own_post(bigint, text) from public;
revoke execute on function public.delete_own_comment(bigint, text) from public;
grant execute on function public.delete_own_post(bigint, text) to anon, authenticated;
grant execute on function public.delete_own_comment(bigint, text) to anon, authenticated;

-- Chuyển quyền tạo/xóa sang tài khoản Supabase Auth.
revoke insert, delete on table public.posts from anon;
revoke insert, delete on table public.comments from anon;
grant select on table public.posts, public.comments to anon;
grant select, insert, delete on table public.posts, public.comments to authenticated;
grant usage, select on sequence public.posts_id_seq, public.comments_id_seq to authenticated;

drop policy if exists "Visitors can create posts" on public.posts;
drop policy if exists "Visitors can create comments" on public.comments;
drop policy if exists "Owners can delete posts" on public.posts;
drop policy if exists "Owners can delete comments" on public.comments;

create policy "Members can create posts"
on public.posts for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and is_demo = false
  and pinned = false
  and score between 0 and 1
  and flair in ('Góp ý', 'Nhận xét', 'Hỏi đáp', 'Chia sẻ')
  and char_length(title) between 3 and 120
  and char_length(excerpt) between 3 and 2000
);

create policy "Members can create comments"
on public.comments for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and char_length(content) between 2 and 1000
);

create policy "Members can delete own posts"
on public.posts for delete
to authenticated
using (user_id = (select auth.uid()));

create policy "Members can delete own comments"
on public.comments for delete
to authenticated
using (user_id = (select auth.uid()));

revoke execute on function public.delete_own_post(bigint, text) from anon, authenticated;
revoke execute on function public.delete_own_comment(bigint, text) from anon, authenticated;

-- Xóa đúng 8 bài mẫu cũ; bài của thành viên có tài khoản không bị ảnh hưởng.
delete from public.posts
where id between 1 and 8 and user_id is null and is_demo = false;

-- Dòng thời gian thử nghiệm kéo dài bốn ngày, đều đặn 5 giờ một bài.
delete from public.posts where is_demo = true;

insert into public.posts (flair, title, excerpt, username, score, created_at, is_demo)
select seed.flair, seed.title, seed.excerpt, seed.username, seed.score,
       now() - make_interval(hours => seed.hours_ago), true
from (values
  (95, 'Nhận xét', 'Lần đầu mở app khá dễ làm quen', 'Các bước chọn tệp và bắt đầu phân tích rõ ràng. Mình không cần đọc hướng dẫn dài vẫn dùng được.', 'mai_beta', 4),
  (90, 'Góp ý', 'Nên cho nghe thử một file mẫu ngay màn hình đầu', 'Có tệp mẫu sẽ giúp người mới hiểu cách đọc kết quả trước khi dùng bản ghi của mình.', 'duy_tester', 5),
  (85, 'Nhận xét', 'Phần giải thích kết quả dễ hiểu hơn mình nghĩ', 'Mình không rành kỹ thuật nhưng vẫn hiểu được vì sao một đoạn âm thanh bị đánh dấu.', 'thu_review', 8),
  (80, 'Góp ý', 'Mong có nút nghe lại ngay tại mốc được đánh dấu', 'Nếu bấm vào mốc mà trình phát nhảy tới đúng đoạn đó thì việc đối chiếu sẽ nhanh hơn.', 'huy_testapp', 7),
  (75, 'Hỏi đáp', 'File m4a từ iPhone có dùng trực tiếp được không?', 'Mình muốn thử vài voice note trên iPhone nhưng chưa rõ có cần đổi định dạng trước không.', 'an_beta', 3),
  (70, 'Nhận xét', 'Chạy ổn trên laptop văn phòng 8GB RAM', 'File gần hai phút xử lý ổn và máy không nóng nhiều. Trải nghiệm tốt hơn mình dự đoán.', 'linh_beta', 10),
  (65, 'Góp ý', 'Thanh tiến trình nên hiển thị thời gian còn lại', 'Khi phân tích file dài mình chưa biết phải chờ bao lâu. Một mốc ước tính sẽ đỡ sốt ruột hơn.', 'minh_beta', 5),
  (60, 'Nhận xét', 'Xử lý local là điểm mình yên tâm nhất', 'Mình thử bằng đoạn phỏng vấn nội bộ và thích việc tệp âm thanh không phải tải lên máy chủ.', 'ngoc_beta', 11),
  (55, 'Góp ý', 'Nên có nút gửi báo cáo lỗi trong màn hình kết quả', 'Nếu kết quả chưa hợp lý, người thử nghiệm có thể góp ý kèm thông tin thiết bị ngay tại đó.', 'nam_review', 6),
  (50, 'Hỏi đáp', 'Có thể lưu lịch sử kết quả chỉ trên máy không?', 'Mình muốn xem lại các lần phân tích trước nhưng vẫn muốn toàn bộ dữ liệu được giữ local.', 'my_beta', 4),
  (45, 'Nhận xét', 'Bản mobile đọc kết quả khá ổn', 'Các mốc vẫn dễ bấm trên màn hình nhỏ. Phần mô tả dài có thể rút gọn thêm một chút.', 'phuc_test', 7),
  (40, 'Góp ý', 'Kéo thả nhiều tệp cùng lúc sẽ tiện hơn', 'Nhóm mình thường kiểm tra một loạt voice note nên rất cần hàng đợi nhiều tệp.', 'quan_review', 6),
  (35, 'Nhận xét', 'Màu cảnh báo vừa đủ rõ, không gây căng mắt', 'Mình dùng liên tục gần một giờ và thấy giao diện khá dễ chịu, các trạng thái vẫn dễ phân biệt.', 'tram_beta', 8),
  (30, 'Góp ý', 'Mong có phím tắt để phát và dừng đoạn đối chiếu', 'Dùng phím cách hoặc phím mũi tên sẽ tiện cho người phải kiểm tra nhiều đoạn liên tiếp.', 'khoa_audio', 4),
  (25, 'Hỏi đáp', 'Âm thanh có nhiều tiếng ồn nền thì nên xử lý thế nào?', 'Mình thử bản ghi ngoài đường và muốn biết có nên lọc nhiễu trước khi đưa vào app hay không.', 'vy_tester', 5),
  (20, 'Nhận xét', 'Báo cáo xuất ra dễ đọc và đủ ý', 'Mình gửi cho một người không dùng app, họ vẫn hiểu các mốc nào cần nghe lại.', 'bao_review', 9),
  (15, 'Góp ý', 'Nên báo rõ giới hạn dung lượng trước khi chọn tệp', 'Hiển thị định dạng và dung lượng tối đa ngay cạnh ô tải lên sẽ tránh phải thử lại.', 'son_beta', 4),
  (10, 'Nhận xét', 'Thử lần đầu với voice note và kết quả khá nhanh', 'Quy trình gọn, không có bước đăng tải lên server nên mình cảm thấy an tâm hơn.', 'yen_test', 7),
  (5, 'Góp ý', 'Mong có chế độ tương phản cao', 'Chữ và đường viền đậm hơn sẽ hữu ích khi dùng laptop ở nơi có ánh sáng mạnh.', 'ha_review', 5),
  (0, 'Nhận xét', 'Tổng thể bản thử nghiệm đang đi đúng hướng', 'Phần phân tích rõ, thao tác gọn và cách giữ dữ liệu local rất phù hợp. Mong team tiếp tục tối ưu tốc độ.', 'tuan_beta', 10)
) as seed(hours_ago, flair, title, excerpt, username, score);

insert into public.comments (post_id, username, content, created_at)
select p.id, seed.username, seed.content, p.created_at + interval '45 minutes'
from (values
  ('Mong có nút nghe lại ngay tại mốc được đánh dấu', 'beta_thu', 'Mình cũng cần thao tác này, nhất là khi file dài hơn vài phút.'),
  ('Xử lý local là điểm mình yên tâm nhất', 'tester_07', 'Đồng ý, đây là lý do chính mình muốn thử app.'),
  ('Kéo thả nhiều tệp cùng lúc sẽ tiện hơn', 'linh_lab', 'Nếu có thêm trạng thái cho từng tệp trong hàng đợi thì càng tốt.'),
  ('Âm thanh có nhiều tiếng ồn nền thì nên xử lý thế nào?', 'khoa_audio', 'Mình nghĩ app nên báo chất lượng đầu vào trước khi phân tích.'),
  ('Tổng thể bản thử nghiệm đang đi đúng hướng', 'mai_beta', 'Mình cũng thấy vậy, phần kết quả hiện dễ hiểu hơn bản đầu.')
) as seed(post_title, username, content)
join public.posts p on p.title = seed.post_title and p.is_demo = true;

-- Hàng đợi hữu hạn cho bảng tin thử nghiệm: tự đăng thêm một bài sau mỗi 5 giờ.
create table if not exists public.demo_post_queue (
  id bigint generated by default as identity primary key,
  flair text not null check (flair in ('Góp ý', 'Nhận xét', 'Hỏi đáp', 'Chia sẻ')),
  title varchar(120) not null unique,
  excerpt text not null,
  username varchar(40) not null,
  score integer not null default 1,
  published_at timestamptz
);

alter table public.demo_post_queue enable row level security;
revoke all on table public.demo_post_queue from anon, authenticated;

truncate table public.demo_post_queue restart identity;

insert into public.demo_post_queue (flair, title, excerpt, username, score)
values
  ('Góp ý', 'Cho phép đổi tên báo cáo trước khi lưu', 'Tên báo cáo theo tên tệp đôi khi khá khó nhớ. Mình muốn đặt lại tên ngay khi xuất.', 'lam_beta', 3),
  ('Nhận xét', 'Thời gian phản hồi trên máy mình khá ổn định', 'Mình thử liên tiếp nhiều file ngắn và chưa gặp tình trạng đứng ứng dụng.', 'quyen_test', 6),
  ('Góp ý', 'Nên có thông báo khi phân tích xong ở tab nền', 'Nếu chuyển sang làm việc khác, một thông báo nhỏ sẽ giúp mình quay lại đúng lúc.', 'viet_review', 4),
  ('Hỏi đáp', 'App có tự nhận biết đoạn âm thanh quá ngắn không?', 'Một số voice note chỉ dài vài giây nên mình muốn biết độ dài tối thiểu để kết quả có ý nghĩa.', 'chi_beta', 3),
  ('Nhận xét', 'Cách phân nhóm dấu hiệu đang khá trực quan', 'Các dấu hiệu được tách rõ nên mình dễ xem lại từng phần mà không bị rối.', 'anh_test', 7),
  ('Góp ý', 'Mong có nút sao chép phần giải thích', 'Mình muốn gửi riêng phần giải thích cho đồng đội mà không cần chụp màn hình.', 'dat_beta', 4),
  ('Nhận xét', 'Bản thử nghiệm dùng tốt với tai nghe', 'Nghe đối chiếu qua tai nghe và chuyển giữa các mốc khá thuận tiện.', 'nhu_review', 5),
  ('Góp ý', 'Nên nhớ thư mục xuất báo cáo gần nhất', 'Việc nhớ thư mục sẽ giảm vài thao tác khi mình phân tích nhiều tệp liên tiếp.', 'long_test', 3);

create or replace function public.publish_next_demo_post()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_item public.demo_post_queue%rowtype;
  last_publish timestamptz;
  new_post_id bigint;
begin
  select max(created_at) into last_publish
  from public.posts
  where is_demo = true;

  if last_publish is not null and now() < last_publish + interval '5 hours' then
    return null;
  end if;

  select * into next_item
  from public.demo_post_queue
  where published_at is null
  order by id
  limit 1
  for update skip locked;

  if next_item.id is null then return null; end if;

  insert into public.posts (flair, title, excerpt, username, score, is_demo)
  values (next_item.flair, next_item.title, next_item.excerpt, next_item.username, next_item.score, true)
  returning id into new_post_id;

  update public.demo_post_queue set published_at = now() where id = next_item.id;
  return new_post_id;
end;
$$;

revoke all on function public.publish_next_demo_post() from public, anon, authenticated;

create extension if not exists pg_cron with schema extensions;
select cron.unschedule(jobid) from cron.job where jobname = 'antifake-voice-demo-feed';
select cron.schedule(
  'antifake-voice-demo-feed',
  '*/15 * * * *',
  'select public.publish_next_demo_post();'
);

-- Các mục trong hàng đợi sẽ bắt đầu được đăng sau 5 giờ kể từ bài gần nhất.
